export const loginSuccessPage1 = '/main/statistics'
export const loginSuccessMenu1 = '/main/center'
export const loginSuccessPage2 = '/main/comprehensive'
export const loginSuccessMenu2 = '/main/supervise'
export const loginSuccessPage3 = '/main/taskList'
export const loginSuccessMenu3 = '/main/task'
export const loginSuccessPage4 = '/main/comprehensive'
export const loginSuccessMenu4 = '/main/supervise'
export const saveDataType = 'query'
// export const baseURL = process.env.NODE_ENV === 'development' ? 'http://118.178.252.219' : ''
export const baseURL = process.env.NODE_ENV === 'development' ? 'http://10.64.4.33' : ''
export const publicPath = '/admin-v1'
export const serverErrorMsg = '服务器端出现错误，请联系管理员'
